global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: 'your_email@example.com'
        send_resolved: true
